# Generated by Django 5.0.1 on 2024-02-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publish_data',
            new_name='publish_date',
        ),
    ]
