# Generated by Django 5.0.1 on 2024-02-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
