# Generated by Django 5.0.1 on 2024-02-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_alter_userfeed_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.feed'),
        ),
    ]
