# Generated by Django 5.0.1 on 2024-01-27 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_system', '0002_feeditem'),
        ('rss_app', '0003_feeditem_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rss_feed_items', to='folder_system.folder'),
        ),
    ]
