# Generated by Django 5.0.1 on 2024-01-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politicalbiasanalysis',
            options={'verbose_name_plural': 'Political Bias Analysis Records'},
        ),
    ]
