# Generated by Django 5.0.1 on 2024-02-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0005_alter_politicalbiasanalysis_biased_sentences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAnalysisResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('article_text_md5', models.CharField(max_length=32)),
                ('sentence_results', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='BiasAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='PoliticalBiasAnalysis',
        ),
    ]
