stages:
  - build
  - test

before_script:
  - cd project_files 
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt

build-job:
  stage: build
  script:
    - echo "Checking project..."
    - python manage.py check  # Check for configuration issues

test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - python manage.py test  # Run tests
