version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./project_files:/app
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - ALLOWED_HOSTS=206.189.22.163
      - DB_HOST=db-unifeed-do-user-15539521-0.c.db.ondigitalocean.com
      - DB_NAME=defaultdb
      - DB_USER=doadmin
      - DB_PASS=AVNS_ErVIjEk4nvskrNn-l6K
      - DB_PORT=25060
