version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SSL_MODE=${SSL_MODE}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
  
  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static
  
  redis:
    image: redis:7.2.4-alpine
    volumes:
      - redis-data:/data
  
  celery:
    build:
      context: .
    command: celery -A unifeed worker --beat --loglevel=info
    volumes:
      - ./project_files:/app
      - ./data/web:/vol/web
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    depends_on:
      - redis

volumes:
  static-data:
  redis-data:
