# Generated by Django 5.0.1 on 2024-01-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_system', '0002_feeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
