# Generated by Django 5.0.1 on 2024-02-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_author_alter_article_publish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='article',
            name='publish_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
