# Generated by Django 5.0.1 on 2024-02-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_publish_date_article_publish_datetime'),
        ('feeds', '0002_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='feed',
        ),
        migrations.AddField(
            model_name='article',
            name='feeds',
            field=models.ManyToManyField(to='feeds.feed'),
        ),
    ]
