# Generated by Django 5.0.1 on 2024-02-16 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_link'),
        ('feeds', '0005_alter_userfeed_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='feeds',
        ),
        migrations.AddField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feeds.feed'),
        ),
    ]
