# Generated by Django 5.0.1 on 2024-01-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedData',
        ),
    ]
