# Generated by Django 5.0.1 on 2024-01-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0003_remove_politicalbiasanalysis_political_bias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalbiasanalysis',
            name='biased_sentences',
            field=models.JSONField(null=True),
        ),
    ]
