# Generated by Django 5.0.1 on 2024-02-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0006_articleanalysisresults_biasanalysis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BiasAnalysis',
        ),
        migrations.AddField(
            model_name='articleanalysisresults',
            name='status',
            field=models.CharField(default='processing', max_length=10),
        ),
    ]
