# Generated by Django 4.2.10 on 2024-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0009_remove_articleanalysisresults_sentence_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleanalysisresults',
            name='bias_conclusion',
            field=models.JSONField(default=dict),
        ),
    ]
