# Generated by Django 4.2.10 on 2024-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0010_articleanalysisresults_bias_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleanalysisresults',
            name='bias_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articleanalysisresults',
            name='bias_conclusion',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
