# Generated by Django 4.2.10 on 2024-02-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0013_alter_aianalysisfeedback_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysisfeedback',
            name='confidence',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
