# Generated by Django 4.2.10 on 2024-02-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_savedarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publisher',
        ),
    ]
